# Generated by Django 2.0.6 on 2018-07-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredienttype',
            name='thumbnail',
        ),
    ]
