# Generated by Django 2.0.6 on 2018-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ingredienttype',
            name='description_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='ingredienttype',
            name='description_fr',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='ingredienttype',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingredienttype',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
