# Generated by Django 2.0.6 on 2018-06-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.png', upload_to='images/avatars/%Y/%m/%d'),
        ),
    ]
