# Generated by Django 2.0.6 on 2018-06-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180624_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookerprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/default_avatar.png', upload_to='images/avatars'),
        ),
    ]
