# Generated by Django 2.0.6 on 2018-06-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default_recipe.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(blank=True, default='default/default_recipe.png', upload_to=''),
        ),
    ]
