# Generated by Django 2.0.6 on 2018-06-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
