# Generated by Django 2.0.6 on 2018-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipecost_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperate',
            name='rate',
            field=models.IntegerField(default=-1),
        ),
    ]
