# Generated by Django 2.0.6 on 2018-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20180702_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeskill',
            options={'ordering': ['value']},
        ),
        migrations.AlterModelOptions(
            name='recipetype',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='recipeskill',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recipetype',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
