# Generated by Django 2.0.6 on 2018-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180625_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/default_recipe.png', upload_to='images/recipes'),
        ),
        migrations.AlterField(
            model_name='recipecost',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
