# Generated by Django 2.0.6 on 2018-06-25 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20180625_1735'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reciperate',
            unique_together={('user', 'recipe')},
        ),
    ]
