# Generated by Django 2.0.6 on 2018-06-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20180625_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(blank=True, default='default/default_recipe.png', upload_to='images/recipes'),
        ),
    ]
