# Generated by Django 2.0.6 on 2018-06-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20180626_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeComment'),
        ),
    ]
