# Generated by Django 2.0.6 on 2018-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20180628_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperate',
            name='rate',
            field=models.FloatField(default=-1),
        ),
    ]
