# Generated by Django 2.0.6 on 2018-06-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20180628_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperate',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='recipes.Recipe'),
        ),
    ]
