# Generated by Django 2.0.6 on 2018-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_fr',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unitmeasure',
            name='name_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unitmeasure',
            name='name_fr',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
