# Generated by Django 2.0.6 on 2018-07-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20180702_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmeasure',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='name_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unitmeasure',
            name='name_fr',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
